{% set version = "6.5.2" %}

package:
  name: importlib_resources
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/importlib_resources/importlib_resources-{{ version }}.tar.gz
  sha256: 185f87adef5bcc288449d98fb4fba07cea78bc036455dd44c5fc4a2fe78fed2c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm >=3.4.1
    # setuptools_scm[toml]
    - toml
  run:
    - python >={{ python_min }}
    - zipp >=3.1.0
  run_constrained:
    - {{ pin_subpackage("importlib-resources", max_pin="x.x.x") }}

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - importlib_resources

outputs:
  - name: importlib_resources
  - name: importlib-resources
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - {{ pin_subpackage("importlib_resources", max_pin="x.x.x") }}
        - python >={{ python_min }}
    test:
      requires:
        - pip
        - python {{ python_min }}
      commands:
        - pip check
      imports:
        - importlib_resources

about:
  home: http://importlib-resources.readthedocs.io
  license: Apache-2.0
  license_file: LICENSE
  summary: Backport of Python 3.7's standard library `importlib.resources`

extra:
  feedstock-name: importlib_resources
  recipe-maintainers:
    - ocefpaf
