{% set version = "6.4.2" %}

package:
  name: importlib_resources
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/importlib_resources/importlib_resources-{{ version }}.tar.gz
  sha256: 6cbfbefc449cc6e2095dd184691b7a12a04f40bc75dd4c55d31c34f174cdf57a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm >=3.4.1
    # setuptools_scm[toml]
    - toml
  run:
    - python >=3.8
    - zipp >=3.1.0
  run_constrained:
    - {{ pin_subpackage("importlib-resources", max_pin="x.x.x") }}

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - importlib_resources

outputs:
  - name: importlib_resources
  - name: importlib-resources
    build:
      noarch: python
    requirements:
      host:
        - python >=3.8
      run:
        - {{ pin_subpackage("importlib_resources", max_pin="x.x.x") }}
        - python >=3.8
    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - importlib_resources

about:
  home: http://importlib-resources.readthedocs.io
  license: Apache-2.0
  license_file: LICENSE
  summary: Backport of Python 3.7's standard library `importlib.resources`

extra:
  feedstock-name: importlib_resources
  recipe-maintainers:
    - ocefpaf
